### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by JonMagon** [romanov/MonoGame-Console#8]
I tried to run, but got System.ArgumentOutOfRangeException in method
`private Form GetGameWindow()
{
     FormCollection winFormsWindow = Application.OpenForms;
     return (Form)Control.FromHandle(winFormsWindow[0].Handle);
}`
Debugger says that Application.OpenForms.Count is 0.

**Comment by JonMagon** [comment]
And now it's working perfectly
`Form winGameWindow = (Form)Control.FromHandle(window.Handle);`

**Comment by romanov** [comment]
@JonMagon so, why open?
